import { access, mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, extname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const output = resolve(root, 'src/client/art.generated.ts')
const assets = {
  ARKNIGHTS_BACKGROUND_LIGHT: 'assets/arknights-garden-day-v3.webp',
  ARKNIGHTS_BACKGROUND_DARK: 'assets/arknights-garden-night-v3.webp',
  ARKNIGHTS_CHARACTER_LEFT: 'assets/arknights-character-left-v3.webp',
  ARKNIGHTS_CHARACTER_RIGHT: 'assets/arknights-character-right-v3.webp',
}

const mimeByExtension = {
  '.png': 'image/png',
  '.webp': 'image/webp',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
}

const missing = []
for (const relative of Object.values(assets)) {
  try {
    await access(resolve(root, relative))
  } catch {
    missing.push(relative)
  }
}

if (missing.length > 0) {
  console.warn(`embed-assets: keeping approval-stage placeholders; missing ${missing.join(', ')}`)
  process.exit(0)
}

const lines = ['/** Generated by scripts/embed-assets.mjs. Do not edit by hand. */']
for (const [name, relative] of Object.entries(assets)) {
  const absolute = resolve(root, relative)
  const mime = mimeByExtension[extname(absolute).toLowerCase()]
  if (mime === undefined) throw new Error(`Unsupported asset type: ${relative}`)
  const base64 = (await readFile(absolute)).toString('base64')
  lines.push(`export const ${name} = ${JSON.stringify(`data:${mime};base64,${base64}`)}`)
}

await mkdir(dirname(output), { recursive: true })
await writeFile(output, `${lines.join('\n')}\n`)
console.log(`embed-assets: wrote ${output}`)
